import type { ThemeConfig } from 'antd'

export const PMS_COLORS = {
  brandStrong: '#5D49F6',
  brandMain: '#7562FF',
  brandSoft: '#AD98EE',
  brandSurface: '#F5F3FF',
  brandBorder: '#DCD6FF',
  page: '#F4F6FB',
  textPrimary: '#27243A',
  textSecondary: '#625D70',
  textTertiary: '#817B90',
  border: '#E6E3EF',
} as const

export const pmsTheme: ThemeConfig = {
  token: {
    colorPrimary: PMS_COLORS.brandMain,
    colorInfo: PMS_COLORS.brandMain,
    colorBgBase: '#FFFFFF',
    colorBgLayout: PMS_COLORS.page,
    colorText: PMS_COLORS.textPrimary,
    colorTextSecondary: PMS_COLORS.textSecondary,
    colorTextTertiary: PMS_COLORS.textTertiary,
    colorBorder: PMS_COLORS.border,
    colorBorderSecondary: '#EFEDF4',
    borderRadius: 6,
    borderRadiusLG: 16,
    controlHeight: 32,
    controlHeightSM: 32,
    controlHeightLG: 32,
    fontSize: 14,
    fontSizeSM: 12,
    fontSizeLG: 16,
    lineHeight: 22 / 14,
    lineHeightSM: 18 / 12,
    lineHeightLG: 24 / 16,
    fontSizeHeading1: 20,
    fontSizeHeading2: 20,
    fontSizeHeading3: 16,
    fontSizeHeading4: 16,
    fontSizeHeading5: 16,
    lineHeightHeading1: 28 / 20,
    lineHeightHeading2: 28 / 20,
    lineHeightHeading3: 24 / 16,
    lineHeightHeading4: 24 / 16,
    lineHeightHeading5: 24 / 16,
    padding: 16,
    paddingSM: 12,
    paddingXS: 8,
    paddingLG: 24,
    fontFamily: '-apple-system, BlinkMacSystemFont, "SF Pro Text", "Segoe UI", "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", sans-serif',
  },
  components: {
    Button: {
      borderRadius: 6,
      contentFontSize: 14,
      contentFontSizeSM: 14,
      contentFontSizeLG: 14,
      primaryShadow: '0 5px 14px rgba(96, 76, 226, .22)',
    },
    Card: {
      borderRadiusLG: 16,
      bodyPadding: 16,
      bodyPaddingSM: 16,
      headerFontSize: 16,
      headerFontSizeSM: 16,
      headerHeight: 48,
      headerHeightSM: 48,
    },
    Modal: {
      borderRadiusLG: 16,
      titleFontSize: 16,
      titleLineHeight: 24 / 16,
    },
    Table: {
      headerBg: PMS_COLORS.brandSurface,
      headerColor: '#514A70',
      rowHoverBg: '#FAF9FF',
      cellFontSize: 12,
      cellFontSizeMD: 12,
      cellFontSizeSM: 12,
      cellPaddingBlock: 8,
      cellPaddingBlockMD: 8,
      cellPaddingBlockSM: 8,
      cellPaddingInline: 12,
      cellPaddingInlineMD: 12,
      cellPaddingInlineSM: 12,
    },
    Tabs: {
      inkBarColor: PMS_COLORS.brandMain,
      itemSelectedColor: PMS_COLORS.brandStrong,
    },
  },
}
