import type { ThemeConfig } from 'antd'

export const PMS_COLORS = {
  brandStrong: '#4D41FF',
  brandMain: '#4D41FF',
  brandSoft: '#AD98EE',
  brandSurface: '#F0EFFF',
  brandBorder: '#DCD6FF',
  page: '#F1EEFF',
  textPrimary: '#000000',
  textSecondary: '#625D70',
  textTertiary: '#817B90',
  border: 'rgba(0, 0, 0, 0.12)',
} as const

export const pmsTheme: ThemeConfig = {
  token: {
    colorPrimary: PMS_COLORS.brandMain,
    colorInfo: PMS_COLORS.brandMain,
    colorBgBase: '#FFFFFF',
    colorBgLayout: PMS_COLORS.page,
    colorText: PMS_COLORS.textPrimary,
    colorTextSecondary: PMS_COLORS.textSecondary,
    colorTextTertiary: PMS_COLORS.textTertiary,
    colorBorder: PMS_COLORS.border,
    colorBorderSecondary: '#EFEDF4',
    borderRadius: 6,
    borderRadiusLG: 16,
    controlHeight: 32,
    controlHeightSM: 32,
    controlHeightLG: 32,
    fontSize: 14,
    fontSizeSM: 12,
    fontSizeLG: 16,
    lineHeight: 20 / 14,
    lineHeightSM: 16 / 12,
    lineHeightLG: 24 / 16,
    fontSizeHeading1: 20,
    fontSizeHeading2: 20,
    fontSizeHeading3: 16,
    fontSizeHeading4: 16,
    fontSizeHeading5: 16,
    lineHeightHeading1: 28 / 20,
    lineHeightHeading2: 28 / 20,
    lineHeightHeading3: 24 / 16,
    lineHeightHeading4: 24 / 16,
    lineHeightHeading5: 24 / 16,
    padding: 16,
    paddingSM: 12,
    paddingXS: 8,
    paddingLG: 24,
    fontFamily: '"PingFang SC", "Microsoft YaHei", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
  },
  components: {
    Button: {
      borderRadius: 6,
      contentFontSize: 14,
      contentFontSizeSM: 14,
      contentFontSizeLG: 14,
      fontWeight: 400,
      paddingInline: 16,
      paddingInlineSM: 16,
      primaryShadow: 'none',
    },
    Form: {
      itemMarginBottom: 12,
      verticalLabelPadding: '0 0 4px',
    },
    Card: {
      borderRadiusLG: 16,
      bodyPadding: 12,
      bodyPaddingSM: 12,
      headerFontSize: 16,
      headerFontSizeSM: 16,
      headerHeight: 48,
      headerHeightSM: 48,
    },
    Modal: {
      borderRadiusLG: 16,
      titleFontSize: 16,
      titleLineHeight: 24 / 16,
    },
    Table: {
      headerBg: PMS_COLORS.brandSurface,
      headerColor: '#514A70',
      rowHoverBg: '#FAF9FF',
      cellFontSize: 14,
      cellFontSizeMD: 14,
      cellFontSizeSM: 14,
      cellPaddingBlock: 9.5,
      cellPaddingBlockMD: 9.5,
      cellPaddingBlockSM: 9.5,
      cellPaddingInline: 12,
      cellPaddingInlineMD: 12,
      cellPaddingInlineSM: 12,
    },
    Tabs: {
      inkBarColor: PMS_COLORS.brandMain,
      itemSelectedColor: PMS_COLORS.brandStrong,
    },
  },
}
